[2024-06-08T03:03:18.877+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-08T03:03:19.547+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_t1.upload_nextDay1 scheduled__2024-06-07T00:00:00+00:00 [queued]>
[2024-06-08T03:03:19.971+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_t1.upload_nextDay1 scheduled__2024-06-07T00:00:00+00:00 [queued]>
[2024-06-08T03:03:19.988+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-08T03:03:21.023+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): upload_nextDay1> on 2024-06-07 00:00:00+00:00
[2024-06-08T03:03:21.710+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=169) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-08T03:03:21.789+0000] {standard_task_runner.py:63} INFO - Started process 192 to run task
[2024-06-08T03:03:21.527+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_t1', 'upload_nextDay1', 'scheduled__2024-06-07T00:00:00+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/Etl_Dag.py', '--cfg-path', '/tmp/tmp3udz1q85']
[2024-06-08T03:03:21.837+0000] {standard_task_runner.py:91} INFO - Job 32: Subtask upload_nextDay1
[2024-06-08T03:03:22.747+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_t1.upload_nextDay1 scheduled__2024-06-07T00:00:00+00:00 [running]> on host 6c00989aad97
[2024-06-08T03:03:23.120+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_t1' AIRFLOW_CTX_TASK_ID='upload_nextDay1' AIRFLOW_CTX_EXECUTION_DATE='2024-06-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-07T00:00:00+00:00'
[2024-06-08T03:03:23.132+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-08T03:03:23.203+0000] {logging_mixin.py:188} INFO - creating nextDayFolder...
[2024-06-08T03:03:23.228+0000] {base.py:84} INFO - Using connection ID 's3_conn' for task execution.
[2024-06-08T03:03:23.230+0000] {connection_wrapper.py:387} INFO - AWS Connection (conn_id='s3_conn', conn_type='aws') credentials retrieved from extra.
[2024-06-08T03:03:25.351+0000] {logging_mixin.py:188} INFO - prefix for next day already exist
[2024-06-08T03:03:25.400+0000] {logging_mixin.py:188} INFO - prefix for next day already exist
[2024-06-08T03:03:25.421+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-08T03:03:25.423+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-08T03:03:25.499+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_t1, task_id=upload_nextDay1, run_id=scheduled__2024-06-07T00:00:00+00:00, execution_date=20240607T000000, start_date=20240608T030319, end_date=20240608T030325
[2024-06-08T03:03:25.671+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-08T03:03:25.699+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
