[2024-06-06T03:19:18.889+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-06T03:19:18.973+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_testConnection_v1.test_first_connection scheduled__2023-01-15T00:00:00+00:00 [queued]>
[2024-06-06T03:19:19.020+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_testConnection_v1.test_first_connection scheduled__2023-01-15T00:00:00+00:00 [queued]>
[2024-06-06T03:19:19.024+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-06T03:19:19.077+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): test_first_connection> on 2023-01-15 00:00:00+00:00
[2024-06-06T03:19:19.162+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_testConnection_v1', 'test_first_connection', 'scheduled__2023-01-15T00:00:00+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/TestConnectionDag.py', '--cfg-path', '/tmp/tmprcrduv59']
[2024-06-06T03:19:19.194+0000] {standard_task_runner.py:91} INFO - Job 39: Subtask test_first_connection
[2024-06-06T03:19:19.186+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=354) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-06T03:19:19.198+0000] {standard_task_runner.py:63} INFO - Started process 359 to run task
[2024-06-06T03:19:19.343+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_testConnection_v1.test_first_connection scheduled__2023-01-15T00:00:00+00:00 [running]> on host fe4af7f6193a
[2024-06-06T03:19:20.028+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_testConnection_v1' AIRFLOW_CTX_TASK_ID='test_first_connection' AIRFLOW_CTX_EXECUTION_DATE='2023-01-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-15T00:00:00+00:00'
[2024-06-06T03:19:20.099+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-06T03:19:20.291+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-06T03:19:20.305+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: <lambda>() missing 1 required positional argument: '_'
[2024-06-06T03:19:20.387+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dag_testConnection_v1, task_id=test_first_connection, run_id=scheduled__2023-01-15T00:00:00+00:00, execution_date=20230115T000000, start_date=20240606T031918, end_date=20240606T031920
[2024-06-06T03:19:20.500+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 39 for task test_first_connection (<lambda>() missing 1 required positional argument: '_'; 359)
[2024-06-06T03:19:20.685+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-06T03:19:20.755+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-06T03:46:20.424+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-06T03:46:20.538+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_testConnection_v1.test_first_connection scheduled__2023-01-15T00:00:00+00:00 [queued]>
[2024-06-06T03:46:20.608+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_testConnection_v1.test_first_connection scheduled__2023-01-15T00:00:00+00:00 [queued]>
[2024-06-06T03:46:20.609+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-06T03:46:20.729+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): test_first_connection> on 2023-01-15 00:00:00+00:00
[2024-06-06T03:46:20.788+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1684) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-06T03:46:20.793+0000] {standard_task_runner.py:63} INFO - Started process 1717 to run task
[2024-06-06T03:46:20.814+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_testConnection_v1', 'test_first_connection', 'scheduled__2023-01-15T00:00:00+00:00', '--job-id', '282', '--raw', '--subdir', 'DAGS_FOLDER/TestConnectionDag.py', '--cfg-path', '/tmp/tmpgr9nclat']
[2024-06-06T03:46:20.824+0000] {standard_task_runner.py:91} INFO - Job 282: Subtask test_first_connection
[2024-06-06T03:46:21.252+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_testConnection_v1.test_first_connection scheduled__2023-01-15T00:00:00+00:00 [running]> on host fe4af7f6193a
[2024-06-06T03:46:21.594+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_testConnection_v1' AIRFLOW_CTX_TASK_ID='test_first_connection' AIRFLOW_CTX_EXECUTION_DATE='2023-01-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-15T00:00:00+00:00'
[2024-06-06T03:46:21.612+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-06T03:46:21.654+0000] {logging_mixin.py:188} INFO - testing task1
[2024-06-06T03:46:21.655+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-06T03:46:21.657+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-06T03:46:21.716+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dag_testConnection_v1, task_id=test_first_connection, run_id=scheduled__2023-01-15T00:00:00+00:00, execution_date=20230115T000000, start_date=20240606T034620, end_date=20240606T034621
[2024-06-06T03:46:21.820+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-06T03:46:21.869+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-06T03:46:21.872+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
