[2024-06-06T04:04:33.778+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-06T04:04:33.828+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_testConnection_v1.test_boto manual__2024-06-06T04:04:30.390351+00:00 [queued]>
[2024-06-06T04:04:33.850+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_testConnection_v1.test_boto manual__2024-06-06T04:04:30.390351+00:00 [queued]>
[2024-06-06T04:04:33.854+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-06T04:04:33.892+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): test_boto> on 2024-06-06 04:04:30.390351+00:00
[2024-06-06T04:04:33.909+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=2221) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-06T04:04:33.913+0000] {standard_task_runner.py:63} INFO - Started process 2228 to run task
[2024-06-06T04:04:33.922+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_testConnection_v1', 'test_boto', 'manual__2024-06-06T04:04:30.390351+00:00', '--job-id', '301', '--raw', '--subdir', 'DAGS_FOLDER/TestConnectionDag.py', '--cfg-path', '/tmp/tmpygp0qu43']
[2024-06-06T04:04:33.926+0000] {standard_task_runner.py:91} INFO - Job 301: Subtask test_boto
[2024-06-06T04:04:34.070+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_testConnection_v1.test_boto manual__2024-06-06T04:04:30.390351+00:00 [running]> on host fe4af7f6193a
[2024-06-06T04:04:34.281+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_testConnection_v1' AIRFLOW_CTX_TASK_ID='test_boto' AIRFLOW_CTX_EXECUTION_DATE='2024-06-06T04:04:30.390351+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-06T04:04:30.390351+00:00'
[2024-06-06T04:04:34.287+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-06T04:04:34.364+0000] {logging_mixin.py:188} INFO - <***.providers.amazon.aws.hooks.s3.S3Hook object at 0x7fa0a9afaf30>
[2024-06-06T04:04:34.424+0000] {base.py:84} INFO - Using connection ID 's3_conn' for task execution.
[2024-06-06T04:04:34.426+0000] {connection_wrapper.py:387} INFO - AWS Connection (conn_id='s3_conn', conn_type='aws') credentials retrieved from extra.
[2024-06-06T04:04:35.460+0000] {logging_mixin.py:188} INFO - True
[2024-06-06T04:04:35.464+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-06T04:04:35.482+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-06T04:04:35.506+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dag_testConnection_v1, task_id=test_boto, run_id=manual__2024-06-06T04:04:30.390351+00:00, execution_date=20240606T040430, start_date=20240606T040433, end_date=20240606T040435
[2024-06-06T04:04:35.584+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-06T04:04:35.626+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-06T04:04:35.635+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
