[2024-06-08T07:11:22.106+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-08T07:11:22.154+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_t1.upload_day manual__2024-06-08T07:11:19.232646+00:00 [queued]>
[2024-06-08T07:11:22.175+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_t1.upload_day manual__2024-06-08T07:11:19.232646+00:00 [queued]>
[2024-06-08T07:11:22.177+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-08T07:11:22.212+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): upload_day> on 2024-06-08 07:11:19.232646+00:00
[2024-06-08T07:11:22.234+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_t1', 'upload_day', 'manual__2024-06-08T07:11:19.232646+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/Etl_Dag.py', '--cfg-path', '/tmp/tmpne0erat3']
[2024-06-08T07:11:22.246+0000] {standard_task_runner.py:91} INFO - Job 41: Subtask upload_day
[2024-06-08T07:11:22.247+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=457) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-08T07:11:22.251+0000] {standard_task_runner.py:63} INFO - Started process 465 to run task
[2024-06-08T07:11:22.372+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_t1.upload_day manual__2024-06-08T07:11:19.232646+00:00 [running]> on host 6c00989aad97
[2024-06-08T07:11:22.597+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_t1' AIRFLOW_CTX_TASK_ID='upload_day' AIRFLOW_CTX_EXECUTION_DATE='2024-06-08T07:11:19.232646+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-08T07:11:19.232646+00:00'
[2024-06-08T07:11:22.600+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-08T07:11:22.632+0000] {logging_mixin.py:188} INFO - from args: None
[2024-06-08T07:11:22.648+0000] {base.py:84} INFO - Using connection ID 's3_conn' for task execution.
[2024-06-08T07:11:22.649+0000] {connection_wrapper.py:387} INFO - AWS Connection (conn_id='s3_conn', conn_type='aws') credentials retrieved from extra.
[2024-06-08T07:11:23.396+0000] {logging_mixin.py:188} INFO - landing prefix for 20240608 already exist
[2024-06-08T07:11:23.403+0000] {logging_mixin.py:188} INFO - transform prefix for 20240608 already exist
[2024-06-08T07:11:23.405+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-08T07:11:23.407+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-08T07:11:23.421+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_t1, task_id=upload_day, run_id=manual__2024-06-08T07:11:19.232646+00:00, execution_date=20240608T071119, start_date=20240608T071122, end_date=20240608T071123
[2024-06-08T07:11:23.456+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-08T07:11:23.498+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-08T07:11:23.505+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
