[2024-06-08T08:25:50.267+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-08T08:25:50.347+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_t1.upload_day manual__2024-06-08T07:11:19.232646+00:00 [queued]>
[2024-06-08T08:25:50.404+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_t1.upload_day manual__2024-06-08T07:11:19.232646+00:00 [queued]>
[2024-06-08T08:25:50.410+0000] {taskinstance.py:2306} INFO - Starting attempt 3 of 3
[2024-06-08T08:25:50.470+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): upload_day> on 2024-06-08 07:11:19.232646+00:00
[2024-06-08T08:25:50.488+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_t1', 'upload_day', 'manual__2024-06-08T07:11:19.232646+00:00', '--job-id', '56', '--raw', '--subdir', 'DAGS_FOLDER/Etl_Dag.py', '--cfg-path', '/tmp/tmpxsrdcflz']
[2024-06-08T08:25:50.496+0000] {standard_task_runner.py:91} INFO - Job 56: Subtask upload_day
[2024-06-08T08:25:50.513+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=3166) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-08T08:25:50.519+0000] {standard_task_runner.py:63} INFO - Started process 3181 to run task
[2024-06-08T08:25:50.663+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_t1.upload_day manual__2024-06-08T07:11:19.232646+00:00 [running]> on host 6c00989aad97
[2024-06-08T08:25:51.091+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_t1' AIRFLOW_CTX_TASK_ID='upload_day' AIRFLOW_CTX_EXECUTION_DATE='2024-06-08T07:11:19.232646+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-08T07:11:19.232646+00:00'
[2024-06-08T08:25:51.094+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-08T08:25:51.120+0000] {logging_mixin.py:188} INFO - from args: None
[2024-06-08T08:25:51.162+0000] {base.py:84} INFO - Using connection ID 's3_conn' for task execution.
[2024-06-08T08:25:51.164+0000] {connection_wrapper.py:387} INFO - AWS Connection (conn_id='s3_conn', conn_type='aws') credentials retrieved from extra.
[2024-06-08T08:25:52.501+0000] {logging_mixin.py:188} INFO - landing prefix for 20240608 already exist
[2024-06-08T08:25:52.517+0000] {logging_mixin.py:188} INFO - transform prefix for 20240608 already exist
[2024-06-08T08:25:52.526+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-08T08:25:52.528+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-08T08:25:52.564+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_t1, task_id=upload_day, run_id=manual__2024-06-08T07:11:19.232646+00:00, execution_date=20240608T071119, start_date=20240608T082550, end_date=20240608T082552
[2024-06-08T08:25:52.665+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-08T08:25:52.697+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-08T08:25:52.705+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
