[2024-06-08T08:34:15.929+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-08T08:34:16.010+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_t1.upload_nextDay1 manual__2024-06-08T07:11:19.232646+00:00 [queued]>
[2024-06-08T08:34:16.043+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_t1.upload_nextDay1 manual__2024-06-08T07:11:19.232646+00:00 [queued]>
[2024-06-08T08:34:16.044+0000] {taskinstance.py:2306} INFO - Starting attempt 4 of 4
[2024-06-08T08:34:16.096+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): upload_nextDay1> on 2024-06-08 07:11:19.232646+00:00
[2024-06-08T08:34:16.146+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=3493) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-08T08:34:16.169+0000] {standard_task_runner.py:63} INFO - Started process 3500 to run task
[2024-06-08T08:34:16.153+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_t1', 'upload_nextDay1', 'manual__2024-06-08T07:11:19.232646+00:00', '--job-id', '61', '--raw', '--subdir', 'DAGS_FOLDER/Etl_Dag.py', '--cfg-path', '/tmp/tmp8m5r2txa']
[2024-06-08T08:34:16.185+0000] {standard_task_runner.py:91} INFO - Job 61: Subtask upload_nextDay1
[2024-06-08T08:34:16.478+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_t1.upload_nextDay1 manual__2024-06-08T07:11:19.232646+00:00 [running]> on host 6c00989aad97
[2024-06-08T08:34:16.839+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_t1' AIRFLOW_CTX_TASK_ID='upload_nextDay1' AIRFLOW_CTX_EXECUTION_DATE='2024-06-08T07:11:19.232646+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-08T07:11:19.232646+00:00'
[2024-06-08T08:34:16.844+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-08T08:34:16.886+0000] {logging_mixin.py:188} INFO - creating nextDayFolder...
[2024-06-08T08:34:16.914+0000] {base.py:84} INFO - Using connection ID 's3_conn' for task execution.
[2024-06-08T08:34:16.920+0000] {connection_wrapper.py:387} INFO - AWS Connection (conn_id='s3_conn', conn_type='aws') credentials retrieved from extra.
[2024-06-08T08:34:18.113+0000] {logging_mixin.py:188} INFO - landing prefix for next day already exist
[2024-06-08T08:34:18.122+0000] {logging_mixin.py:188} INFO - transfrom prefix for next day already exist
[2024-06-08T08:34:18.123+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-08T08:34:18.126+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-08T08:34:18.163+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_t1, task_id=upload_nextDay1, run_id=manual__2024-06-08T07:11:19.232646+00:00, execution_date=20240608T071119, start_date=20240608T083416, end_date=20240608T083418
[2024-06-08T08:34:18.276+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-08T08:34:18.334+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-08T08:34:18.338+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
