[2024-06-08T08:39:09.047+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-08T08:39:09.078+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_t1.upload_nextDay1 manual__2024-06-08T07:11:19.232646+00:00 [queued]>
[2024-06-08T08:39:09.095+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_t1.upload_nextDay1 manual__2024-06-08T07:11:19.232646+00:00 [queued]>
[2024-06-08T08:39:09.096+0000] {taskinstance.py:2306} INFO - Starting attempt 5 of 5
[2024-06-08T08:39:09.121+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): upload_nextDay1> on 2024-06-08 07:11:19.232646+00:00
[2024-06-08T08:39:09.135+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=3694) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-08T08:39:09.138+0000] {standard_task_runner.py:63} INFO - Started process 3704 to run task
[2024-06-08T08:39:09.139+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_t1', 'upload_nextDay1', 'manual__2024-06-08T07:11:19.232646+00:00', '--job-id', '71', '--raw', '--subdir', 'DAGS_FOLDER/Etl_Dag.py', '--cfg-path', '/tmp/tmple343kzq']
[2024-06-08T08:39:09.148+0000] {standard_task_runner.py:91} INFO - Job 71: Subtask upload_nextDay1
[2024-06-08T08:39:09.257+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_t1.upload_nextDay1 manual__2024-06-08T07:11:19.232646+00:00 [running]> on host 6c00989aad97
[2024-06-08T08:39:09.506+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_t1' AIRFLOW_CTX_TASK_ID='upload_nextDay1' AIRFLOW_CTX_EXECUTION_DATE='2024-06-08T07:11:19.232646+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-08T07:11:19.232646+00:00'
[2024-06-08T08:39:09.507+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-08T08:39:09.559+0000] {logging_mixin.py:188} INFO - creating nextDayFolder...
[2024-06-08T08:39:09.603+0000] {base.py:84} INFO - Using connection ID 's3_conn' for task execution.
[2024-06-08T08:39:09.610+0000] {connection_wrapper.py:387} INFO - AWS Connection (conn_id='s3_conn', conn_type='aws') credentials retrieved from extra.
[2024-06-08T08:39:10.687+0000] {logging_mixin.py:188} INFO - landing prefix for next day already exist
[2024-06-08T08:39:10.694+0000] {logging_mixin.py:188} INFO - transfrom prefix for next day already exist
[2024-06-08T08:39:10.695+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-08T08:39:10.698+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-08T08:39:10.709+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_t1, task_id=upload_nextDay1, run_id=manual__2024-06-08T07:11:19.232646+00:00, execution_date=20240608T071119, start_date=20240608T083909, end_date=20240608T083910
[2024-06-08T08:39:10.769+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-08T08:39:10.804+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-08T08:39:10.810+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
