[2024-06-09T10:50:48.800+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-09T10:50:48.864+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_t1.upload_day manual__2024-06-09T10:50:44.895269+00:00 [queued]>
[2024-06-09T10:50:48.894+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_t1.upload_day manual__2024-06-09T10:50:44.895269+00:00 [queued]>
[2024-06-09T10:50:48.895+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-09T10:50:48.943+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): upload_day> on 2024-06-09 10:50:44.895269+00:00
[2024-06-09T10:50:48.971+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=910) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-09T10:50:48.973+0000] {standard_task_runner.py:63} INFO - Started process 918 to run task
[2024-06-09T10:50:48.974+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_t1', 'upload_day', 'manual__2024-06-09T10:50:44.895269+00:00', '--job-id', '86', '--raw', '--subdir', 'DAGS_FOLDER/Etl_Dag.py', '--cfg-path', '/tmp/tmpenpx19ku']
[2024-06-09T10:50:48.977+0000] {standard_task_runner.py:91} INFO - Job 86: Subtask upload_day
[2024-06-09T10:50:49.095+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_t1.upload_day manual__2024-06-09T10:50:44.895269+00:00 [running]> on host 6c00989aad97
[2024-06-09T10:50:49.299+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_t1' AIRFLOW_CTX_TASK_ID='upload_day' AIRFLOW_CTX_EXECUTION_DATE='2024-06-09T10:50:44.895269+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-09T10:50:44.895269+00:00'
[2024-06-09T10:50:49.301+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-09T10:50:49.357+0000] {logging_mixin.py:188} INFO - from args: None
[2024-06-09T10:50:49.381+0000] {base.py:84} INFO - Using connection ID 's3_conn' for task execution.
[2024-06-09T10:50:49.382+0000] {connection_wrapper.py:387} INFO - AWS Connection (conn_id='s3_conn', conn_type='aws') credentials retrieved from extra.
[2024-06-09T10:50:51.470+0000] {logging_mixin.py:188} INFO - landing prefix for 20240609 already exist
[2024-06-09T10:50:51.478+0000] {logging_mixin.py:188} INFO - transform prefix for 20240609 already exist
[2024-06-09T10:50:51.483+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-09T10:50:51.485+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-09T10:50:51.502+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_t1, task_id=upload_day, run_id=manual__2024-06-09T10:50:44.895269+00:00, execution_date=20240609T105044, start_date=20240609T105048, end_date=20240609T105051
[2024-06-09T10:50:51.566+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-09T10:50:51.593+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-09T10:50:51.597+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
