[2024-06-09T10:50:48.893+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-09T10:50:48.939+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_t1.transformTest manual__2024-06-09T10:50:44.895269+00:00 [queued]>
[2024-06-09T10:50:48.994+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_t1.transformTest manual__2024-06-09T10:50:44.895269+00:00 [queued]>
[2024-06-09T10:50:48.995+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-09T10:50:49.038+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transformTest> on 2024-06-09 10:50:44.895269+00:00
[2024-06-09T10:50:49.047+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_t1', 'transformTest', 'manual__2024-06-09T10:50:44.895269+00:00', '--job-id', '87', '--raw', '--subdir', 'DAGS_FOLDER/Etl_Dag.py', '--cfg-path', '/tmp/tmpv54mnttp']
[2024-06-09T10:50:49.054+0000] {standard_task_runner.py:91} INFO - Job 87: Subtask transformTest
[2024-06-09T10:50:49.068+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=912) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-09T10:50:49.074+0000] {standard_task_runner.py:63} INFO - Started process 919 to run task
[2024-06-09T10:50:49.166+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_t1.transformTest manual__2024-06-09T10:50:44.895269+00:00 [running]> on host 6c00989aad97
[2024-06-09T10:50:49.350+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_t1' AIRFLOW_CTX_TASK_ID='transformTest' AIRFLOW_CTX_EXECUTION_DATE='2024-06-09T10:50:44.895269+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-09T10:50:44.895269+00:00'
[2024-06-09T10:50:49.351+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-09T10:50:49.401+0000] {base.py:84} INFO - Using connection ID 's3_conn' for task execution.
[2024-06-09T10:50:49.402+0000] {connection_wrapper.py:387} INFO - AWS Connection (conn_id='s3_conn', conn_type='aws') credentials retrieved from extra.
[2024-06-09T10:50:51.480+0000] {logging_mixin.py:188} INFO - no files detected
[2024-06-09T10:50:51.481+0000] {logging_mixin.py:188} INFO - exiting...
[2024-06-09T10:50:51.482+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-09T10:50:51.484+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-09T10:50:51.501+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_t1, task_id=transformTest, run_id=manual__2024-06-09T10:50:44.895269+00:00, execution_date=20240609T105044, start_date=20240609T105048, end_date=20240609T105051
[2024-06-09T10:50:51.580+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-09T10:50:51.594+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
